config/routes.rb
Rails.application.routes.draw do

  resources :users do
    get :movies, on: :member
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :movies
  resources :ratings, only: [:create, :update, :destroy]
  root 'movies#index'
  match '/signup', to: 'users#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/signin', to: 'sessions#new', via: 'get'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_filter :check_if_user_is_signed, only: [:new, :create, :update, :destroy]

  def index
    @movies = Movie.all.includes(:user)
    @movies = params[:sort].present? ? @movies.custom_order(params[:by]) : @movies.custom_order("created_at")
  end

  def show
    @rating = Rating.find_or_initialize_by(user: current_user, movie: @movie)
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = current_user.movies.new(movie_params)
    if @movie.save
      redirect_to root_url, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end

  def update
    if @movie.update(movie_params)
      redirect_to root_url, notice: 'Movie was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_url, notice: 'Movie was successfully destroyed.'
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :published_at)
    end

    def check_if_user_is_signed
      redirect_to signin_url, notice: "You must be logged in to do that" unless signed_in?
    end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_filters.html.haml
%p
  Sort by:
  = link_to "Likes", params.merge(sort: true, by: "likes_count")
  |
  = link_to "Hates", params.merge(sort: true, by: "hates_count")
  |
  = link_to "Date", params.merge(sort: true, by: "published_at")
  |
  = link_to "Most voted", params.merge(sort: true, by: "ratings_count")
  |
  = link_to "Best Rated", params.merge(sort: true, by: "likes_to_ratings_ratio")

app/views/movies/_form.html.haml
= simple_form_for @movie do |f|
  = f.input :title
  = f.input :description
  = f.input :published_at, start_year: Date.parse("january 1 1900").year, end_year: Time.now.year, order: [:day, :month, :year]
  = f.submit "Post movie!", class: "movie-submit"

app/views/movies/_movie.html.haml
.movie-wrapper
  %h3
    = movie.title.titleize
  %h4.author
    Posted by
    = link_to movie.user.name.humanize, movies_user_path(movie.user)
    = "#{time_ago_in_words movie.created_at} ago."
  %p.description
    = movie.description

  - if signed_in?
    = "Be the first to vote for this movie:" unless(movie.ratings_count > 0 || current_user.has_created?(movie))
    %p.ratings
      = current_user.has_liked?(movie) || current_user.has_created?(movie) ? rating_counts_pluralizer(movie, "like") : render(partial: 'ratings/form', locals: { movie: movie, value: "like" })
    %p.ratings
      = current_user.has_hated?(movie) || current_user.has_created?(movie) ? rating_counts_pluralizer(movie, "hate") : render(partial: 'ratings/form', locals: { movie: movie, value: "hate" })

    - if current_user.has_rated?(movie)
      = raw link_to_undo(current_user.get_rating_for(movie))

  - else
    %p.ratings
      = rating_counts_pluralizer(movie, "like")
    %p.ratings
      = rating_counts_pluralizer(movie, "hate")

app/views/movies/index.html.haml
= render 'movies/filters'
= (render @movies) || content_tag(:p, "No movies found!")

app/views/movies/show.html.haml
%h3
  = @movie.title.titleize
%h4
  Posted by
  = @movie.user.name.humanize
  = "#{time_ago_in_words @movie.created_at} ago."

%p
  = @movie.description


- if signed_in?

  = "Be the first to vote for this movie:" if @movie.ratings_count == 0

  - if @rating.persisted? && @rating.positive?
    = "#{pluralize(@movie.likes_count, "like")}"
  - else
    = simple_form_for(@rating) do |f|
      = f.input :positive, as: :hidden, input_html: { value: true }
      = f.input :movie_id, as: :hidden
      = f.submit "#{pluralize(@movie.likes_count, "like")}"

  - if @rating.persisted? && @rating.negative?
    = "#{pluralize(@movie.hates_count, "hate")}"
  - else
    = simple_form_for(@rating) do |f|
      = f.input :positive, as: :hidden, input_html: { value: false }
      = f.input :movie_id, as: :hidden
      = f.submit "#{pluralize(@movie.hates_count, "hate")}"

%hr

  - if @rating.persisted?
    - if @rating.positive
      You like this movie
      |
      = link_to "Unlike!", @rating, method: :delete
    - else
      You hate this movie
      |
      = link_to "Unhate", @rating, method: :delete


= link_to "Back", :back